### PR TITLE
Feature/add calc

### PR DESCRIPTION
**Pull request by Rosmery0**
# Task Description
Add Calc
Add github action CI 
# Notes
none
#Dependencies
none
# CheckList
- [x] Unit Test
- [x] Integrated Test
- [] Linter
- [x] Doc Updated
- [] Deployment Config

### CODE REVIEW

**Comment by Maestroabel** [comment]
Ready

**Comment by EnmanuelUrena** [comment]
Listo

**Review by EnmanuelUrena — APPROVED** [review]

**Comment by Maestroabel** [comment]
Ready

**Comment by Rosmery0** [comment]
Listo

**Review by Rosmery0 — COMMENTED** [review]
Está listo

**Review by Maestroabel — APPROVED** [review]
Ready

**Pull request merged**
